### ISSUE TITLE
Push tags to PyPI

### ISSUE THREAD

**Issue by LukeShortCloud** [ekultails/card_games_converter#11]
TravisCI should automatically publish new packages to PyPI when a new version tag in GitHub is created.

Something like this should work:

```
deploy:
...
   on:
     tags: true
```

See: https://docs.travis-ci.com/user/deployment/
